name: Build & Deploy Spring app

on:
  push:
    branches:
      - ["main"]
  pull_request:
    branches:
      - ["main"]

jobs:
  build:

    name: Build & Deploy Spring app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
          cache: maven

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
